{% set name = "apache-airflow-providers-weaviate" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_weaviate-{{ version }}.tar.gz
  sha256: a6279c4a4df8c8f2eec93d14a951f3cb25e42e0ce5fbcf8f6368e9cc6cd385cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.8.0
    - httpx >=0.25.0
    - weaviate-client >=4.4.0,!=4.16.7
    # more restrictive for python >=3.13
    - pandas >=2.1.2

test:
  imports:
    - airflow.providers.weaviate
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-weaviate for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-weaviate/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
