{% set name = "apache-airflow-providers-weaviate" %}
{% set version = "3.2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_weaviate-{{ version }}.tar.gz
  sha256: 092ce7f6e651d216554a0d0b70eeb3794ad3ec1170b7ddf0e71259d54afde76a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - httpx >=0.25.0
    - weaviate-client >=4.4.0
    - pandas >=2.1.2

test:
  imports:
    - airflow.providers.weaviate
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-weaviate for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/weaviate/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-weaviate/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
